apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./app
  - ./db

images:
  - name: cr.hday/image
    newName: cr.hday.io/hday/milestone-timeline
    newTag: "r23035876196"

patches:
  - target:
      kind: Deployment
      name: milestone-timeline
    patch: |
      - op: add
        path: /spec/template/spec/affinity/podAffinity/requiredDuringSchedulingIgnoredDuringExecution/-
        value: 
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
              app.kubernetes.io/instance: prod
          topologyKey: kubernetes.io/hostname
