apiVersion: v1
kind: Secret
metadata:
  name: milestone-timeline-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_eM14yBuokCpZ@ep-rapid-dew-a18yq3hl-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
