apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels: {}
  serviceName: postgres
  template:
    metadata:
      labels: {}
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: milestone
            - name: POSTGRES_USER
              value: milestone
            - name: POSTGRES_PASSWORD
              value: milestone
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        storageClassName: app
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
